PUT http://localhost:5000/api/users

###
POST http://localhost:5000/api/users
Content-Type: application/json

{
			"name": "Isabel",
			"email": "isabel@gmail.com",
			"password": "343223"
}

###
GET http://localhost:5000/api/shops

###
POST http://localhost:5000/api/shops/

###

GET http://localhost:5000/api/auth
// get log in user

###
POST http://localhost:5000/api/auth
// log in user

###
GET http://localhost:5000/api/posts/

###
POST http://localhost:5000/api/posts/

###
PUT http://localhost:5000/api/posts/1

###
DELETE http://localhost:5000/api/posts/1