GET http://localhost:3000/posts


###

POST http://localhost:3000/posts
Content-Type: application/json

{
			"title": "async!",
			"description": "try catch trial"
}

###
GET http://localhost:3000/posts/5f59362dbb7043330803aa84



###
DELETE http://localhost:3000/posts/5f59362dbb7043330803aa84

###
PUT http://localhost:3000/api/courses/1
Content-Type: application/json

{
		"name": "new course 2"
}

###

DELETE http://localhost:3000/api/courses/1
Content-Type: application/json

{
		"name": "new course 2"
}
